# Generated by Django 2.1.2 on 2019-02-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcontract',
            name='status',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
