# Generated by Django 2.1.2 on 2019-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='id_user',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
