# Generated by Django 2.1.2 on 2019-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='id_award',
        ),
        migrations.AlterField(
            model_name='award',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='award',
            name='email_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='id_institution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='name_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
