# Generated by Django 2.1.2 on 2019-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20190113_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
