# Generated by Django 2.1.2 on 2019-01-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_award_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='verfied',
            new_name='verified',
        ),
    ]
