# Generated by Django 2.1.2 on 2019-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contract', models.IntegerField()),
                ('id_company', models.IntegerField()),
                ('id_time_contract', models.IntegerField()),
                ('name_contract', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
