from django.db import models

class Task(models.Model):
	id_company = models.IntegerField(default = 0) #(int)
	id_kpi_category = models.IntegerField(default = 0) #(int)
	id_kpi_definition = models.IntegerField(default = 0) #(int)
	name = models.CharField(max_length = 255) #(char)
	description = models.TextField(null = True) #(text)
	priority = models.IntegerField(default = 0) #(int)
	dateadded = models.DateField(auto_now = True) #(date)
	duedate = models.DateField(null = True) #(date)
	datefinished = models.DateField(null = True) #(dated)
	addedfrom = models.IntegerField(default = 0) #(int)
	status = models.IntegerField(default = 0) #(int)
	recurring_type = models.IntegerField(default = 0) #(int)
	repeat_every = models.IntegerField(default = 0) #(int)
	recurring = models.IntegerField(default = 0) #(int)
	is_recurring_from = models.IntegerField() #(int)
	cycles = models.IntegerField(default = 0) #(int)
	total_cycles = models.IntegerField(default = 0) #(int)
	custom_recurring = models.IntegerField(default = 0) #(int)
	milestoneIndex = models.IntegerField(default = 0) #(int)
	kanban_orderIndex = models.IntegerField(default = 0) #(int)
	milestone_order = models.IntegerField(default = 0) #(int)
	deadline_notified = models.IntegerField(null = True) #(int)
	created_at = models.DateTimeField(auto_now_add = True)
