# Generated by Django 2.1.2 on 2019-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_created_goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_goal',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log_goal',
            name='update_at',
            field=models.CharField(default='**', max_length=255),
        ),
    ]
