# Generated by Django 2.1.2 on 2019-02-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_sign', '0002_remove_employeesign_id_employee_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesign',
            name='id_employee_sign',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
