# Generated by Django 2.1.2 on 2019-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_sign', '0003_employeesign_id_employee_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesign',
            name='id_company',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='id_contract',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='id_employee_sign',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='id_hirarchy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='id_hirarchy_history',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='id_job_contract',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
