# Generated by Django 2.1.2 on 2019-03-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_sign', '0006_auto_20190208_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesign',
            name='reason',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeesign',
            name='status_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
