# Generated by Django 2.1.2 on 2019-03-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('comp_id', models.IntegerField()),
                ('descript', models.TextField()),
                ('sallary', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('pref_language', models.CharField(max_length=30)),
                ('dresscode', models.CharField(max_length=20)),
                ('worktime', models.IntegerField()),
                ('tunjangan', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jobs', models.IntegerField()),
                ('id_applicant', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('descript', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
