# Generated by Django 2.1.2 on 2019-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(),
        ),
    ]
