# Generated by Django 2.1.2 on 2019-04-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20190404_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='position',
            field=models.CharField(max_length=1000),
        ),
    ]
