# Generated by Django 2.1.2 on 2019-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warna_goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warna_goal',
            name='id_company',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warna_goal',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
