# Generated by Django 2.1.2 on 2019-02-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCR_Reader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_img',
        ),
        migrations.DeleteModel(
            name='User_img',
        ),
    ]
