# Generated by Django 2.1.2 on 2020-02-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_account', '0006_auto_20190423_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('feature_id', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('qty_license', models.IntegerField(default=0)),
                ('term_license', models.IntegerField(default=0)),
                ('expire_date_license', models.DateField()),
                ('status_license', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_account.Business')),
            ],
            options={
                'verbose_name': 'Billing License',
                'verbose_name_plural': 'Billing License',
                'db_table': 'billing_license',
            },
        ),
    ]
