# Generated by Django 2.1.2 on 2020-02-28 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_license', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinglicense',
            old_name='account_id',
            new_name='id_company',
        ),
        migrations.AddField(
            model_name='billinglicense',
            name='start_date_license',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='billinglicense',
            name='expire_date_license',
            field=models.DateField(blank=True),
        ),
    ]
