# Generated by Django 2.1.2 on 2019-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rec', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=50)),
                ('email_comp', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
