# Generated by Django 2.1.2 on 2019-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id_company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
