# Generated by Django 2.1.2 on 2019-01-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_auto_20190131_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='id_job_contract',
        ),
    ]
