# Generated by Django 2.1.2 on 2019-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_remove_level_id_job_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id_company',
            field=models.IntegerField(),
        ),
    ]
