# Generated by Django 2.1.2 on 2019-01-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_auto_20190131_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id_company',
            field=models.IntegerField(default=None),
        ),
    ]
