# Generated by Django 2.1.2 on 2019-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True)),
                ('token_web', models.CharField(default='xxx', max_length=1000)),
                ('token_phone', models.CharField(default='xxx', max_length=1000)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
