# Generated by Django 2.1.2 on 2019-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_api', '0002_multiplelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_api',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
