from django.db import models

class GoalFiles(models.Model):
	id_goal  = models. IntegerField()  # (int)
	id_hierarchy  = models. IntegerField()  # (int)
	id_company  = models. IntegerField()  # (int)
	id_user  = models. IntegerField()  # (int)
	subject  = models. CharField(max_length = 255)  # (char)
	full_name  = models. CharField(max_length = 255)  # (char)
	description  = models. TextField()  # (text)
	filetype  = models. TextField()  # (text)
	dateadd  = models. DateTimeField(auto_now_add = True)  # (date)
	last_activity  = models. DateTimeField(auto_now = True)  # (date)
	external  = models. IntegerField()  # (text)
	external_link  = models. IntegerField()  # (text)
	thumbnail_link  = models. IntegerField()  #(text)

	# id_goal = models.IntegerField() #(int)
	# id_company = models.IntegerField() #(int)
	# id_hierarchy = models.IntegerField() #(int)
	# id_user = models.IntegerField() #(int)
	# division = models.CharField(max_length = 255) #(char)
	# full_name = models.CharField(max_length  = 255) #(char)
	# description_key = models.CharField(max_length =255) #(char)
	# addtional_data = models.TextField() #(text)
	# created_date = models.DateTimeField(auto_now_add = True) #(date)
