# Generated by Django 2.1.7 on 2020-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=60)),
                ('follower', models.ManyToManyField(blank=True, related_name='follower', to='registrations.Register')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to='registrations.Register')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=60)),
                ('friend_list', models.ManyToManyField(blank=True, related_name='friend_list', to='registrations.Register')),
                ('friend_request', models.ManyToManyField(blank=True, related_name='friend_request', to='registrations.Register')),
                ('waiting_for_response', models.ManyToManyField(blank=True, related_name='waiting_for_response', to='registrations.Register')),
            ],
        ),
    ]
