# Generated by Django 2.1.2 on 2019-08-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=60)),
                ('registers', models.ManyToManyField(blank=True, related_name='friend_list', to='registrations.Register')),
            ],
        ),
    ]
