# Generated by Django 2.1.2 on 2019-08-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='pending_registers',
            field=models.ManyToManyField(blank=True, related_name='pending_friend_list', to='registrations.Register'),
        ),
    ]
