# Generated by Django 2.1.2 on 2019-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
        ('friends', '0002_friends_pending_registers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='pending_registers',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_request',
            field=models.ManyToManyField(blank=True, related_name='friend_request', to='registrations.Register'),
        ),
        migrations.AddField(
            model_name='friends',
            name='waiting_for_response',
            field=models.ManyToManyField(blank=True, related_name='waiting_for_response', to='registrations.Register'),
        ),
    ]
