from django.db import models

class Kpi(models.Model):
	id_kpi_category = models.IntegerField()
	nama_kpi= models.CharField(max_length = 255)
	id_goal = models.IntegerField()
	id_company = models.IntegerField()
	description = models.TextField()
	time_measurement = models.IntegerField()
	operator = models.CharField(max_length = 255)
	bobot = models.FloatField()
	status = models.IntegerField()
	update_at = models.DateTimeField(auto_now = True)
	created_at = models.DateTimeField(auto_now_add = True)

	# id_company (int)
	# id_goal (int)
	# id_kpi_category (int)
	# name_kpi (char)
	# description (text)
	# time_measurment (int)
	# operator (char)
	# bobot (float)
	# status (int)
	# crated_date (date)