# Generated by Django 2.1.2 on 2019-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_company', models.IntegerField(blank=True, null=True)),
                ('id_job_contract', models.IntegerField(blank=True, null=True)),
                ('name_company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email_company', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('verfied', models.CharField(max_length=3)),
                ('url_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('satified', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
