# Generated by Django 2.1.2 on 2019-01-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiences',
            old_name='verfied',
            new_name='verified',
        ),
    ]
