# Generated by Django 2.1.2 on 2019-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiences',
            old_name='satified',
            new_name='satisfied',
        ),
        migrations.AlterField(
            model_name='experiences',
            name='id_company',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='id_job_contract',
            field=models.IntegerField(),
        ),
    ]
