# Generated by Django 2.1.2 on 2019-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20190208_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='present_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
