# Generated by Django 2.1.2 on 2019-08-09 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedsObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=60)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('comments_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikesNComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='', max_length=60)),
                ('feedsobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.FeedsObj')),
            ],
        ),
    ]
