# Generated by Django 2.1.2 on 2019-08-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesncomments',
            name='user_id',
        ),
    ]
