# Generated by Django 2.1.2 on 2019-08-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_likesncomments_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesncomments',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
