# Generated by Django 2.1.2 on 2019-08-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_likesncomments_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesncomments',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='likesncomments',
            name='feedsobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.FeedsObj'),
        ),
        migrations.AlterField(
            model_name='likesncomments',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likesncomments',
            name='user_name',
            field=models.CharField(max_length=60),
        ),
    ]
