# Generated by Django 2.1.2 on 2019-08-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20190809_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesncomments',
            name='feedsobj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.FeedsObj'),
        ),
    ]
