# Generated by Django 2.1.2 on 2019-08-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_feedsobj_comments_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=60)),
                ('FeedsObjs', models.ManyToManyField(to='feeds.FeedsObj')),
            ],
        ),
    ]
