# Generated by Django 2.1.2 on 2019-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='type_name',
            field=models.CharField(max_length=7),
        ),
    ]
