# Generated by Django 2.1.2 on 2019-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='no_ktp',
            field=models.BigIntegerField(),
        ),
    ]
