# Generated by Django 2.1.2 on 2019-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_img', '0002_auto_20190206_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='nomor',
            field=models.CharField(max_length=20),
        ),
    ]
