# Generated by Django 2.1.2 on 2019-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task_assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kpi', models.IntegerField()),
                ('id_kpi_assign', models.IntegerField()),
                ('id_task', models.IntegerField()),
                ('id_hierarchy', models.IntegerField()),
                ('id_type', models.IntegerField()),
                ('actual_status', models.IntegerField()),
                ('actual', models.FloatField()),
                ('file', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
