# Generated by Django 2.1.2 on 2019-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_assign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_assign',
            old_name='id_kpi',
            new_name='id_kpi_category',
        ),
        migrations.RemoveField(
            model_name='task_assign',
            name='file',
        ),
        migrations.AddField(
            model_name='task_assign',
            name='id_company',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_assign',
            name='id_kpi_definition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_assign',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_assign',
            name='actual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='task_assign',
            name='actual_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_assign',
            name='id_hierarchy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_assign',
            name='id_kpi_assign',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_assign',
            name='id_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_assign',
            name='id_type',
            field=models.IntegerField(default=0),
        ),
    ]
