# Generated by Django 2.1.2 on 2019-05-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal_assign',
            old_name='id_level',
            new_name='id_type',
        ),
        migrations.RemoveField(
            model_name='goal_assign',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='goal_assign',
            name='sisa_allocation',
        ),
        migrations.RemoveField(
            model_name='goal_assign',
            name='sisa_percent',
        ),
        migrations.RemoveField(
            model_name='goal_assign',
            name='time_allocation',
        ),
    ]
