# Generated by Django 2.1.2 on 2019-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('primary_phone', models.IntegerField(blank=True, null=True)),
                ('primary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('id_country', models.IntegerField(blank=True, null=True)),
                ('id_regions', models.IntegerField(blank=True, null=True)),
                ('id_city', models.IntegerField(blank=True, null=True)),
                ('id_business_type', models.IntegerField(blank=True, null=True)),
                ('tax_num', models.IntegerField(blank=True, null=True)),
                ('logo_path', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banned_type', models.CharField(blank=True, max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
                ('parent_company', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
