# Generated by Django 2.1.2 on 2019-01-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='id_type',
        ),
        migrations.AddField(
            model_name='business',
            name='id_business_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='id_city',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='id_country',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='id_regions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
