# Generated by Django 2.1.2 on 2019-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0002_auto_20190113_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
