# Generated by Django 2.1.2 on 2019-02-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0002_remove_business_parent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='parent_company',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
