# Generated by Django 2.1.2 on 2019-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0003_business_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='parent_company',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
