# Generated by Django 2.1.2 on 2019-04-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_account', '0005_auto_20190320_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo_path',
            field=models.TextField(blank=True, default='http://dev-user-admin.mindzzle.com/static/img/blank_business.503c6c8.jpg', null=True),
        ),
    ]
