# Generated by Django 2.1.2 on 2019-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('percent', models.IntegerField()),
                ('parent_goal', models.IntegerField()),
                ('id_hierarchy', models.IntegerField()),
                ('id_type_goal', models.IntegerField()),
                ('max_jobdesk', models.IntegerField()),
                ('max_bonus', models.IntegerField()),
                ('status', models.CharField(max_length=3)),
                ('id_review_scheduler', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('id_level', models.IntegerField()),
                ('time_allocation', models.IntegerField()),
                ('sisa_allocation', models.IntegerField()),
            ],
        ),
    ]
