# Generated by Django 2.1.2 on 2019-02-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='max_jobdesk',
            new_name='max_jobdesk',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='percent',
            new_name='percent',
        ),
    ]
