# Generated by Django 2.1.2 on 2019-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20190215_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.IntegerField()),
                ('id_time_period', models.IntegerField()),
                ('id_category_goal', models.IntegerField()),
                ('spt_priority', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('create_hierarchy', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
