# Generated by Django 2.1.2 on 2019-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_auto_20190527_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.IntegerField()),
                ('progress_from_task', models.IntegerField()),
                ('id_category_goal', models.IntegerField()),
                ('id_warna_goal', models.IntegerField()),
                ('create_hierarchy', models.IntegerField()),
                ('create_user', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
