# Generated by Django 2.1.2 on 2019-10-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comp', models.IntegerField()),
                ('id_hierarchy', models.IntegerField(unique=True)),
                ('approval1', models.IntegerField()),
                ('approval2', models.IntegerField()),
                ('attendance1', models.IntegerField(default=0)),
                ('attendance2', models.IntegerField(default=0)),
                ('payroll1', models.IntegerField(default=0)),
                ('payroll2', models.IntegerField(default=0)),
            ],
        ),
    ]
