# Generated by Django 2.1.2 on 2019-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='id_hierarchy',
            field=models.IntegerField(unique=True),
        ),
    ]
