# Generated by Django 2.1.2 on 2019-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.IntegerField()),
                ('id_hierarchy', models.IntegerField(unique=True)),
                ('tipe_group', models.IntegerField(default=1)),
                ('parent_group', models.IntegerField(default=0)),
                ('set_manage', models.IntegerField(default=0)),
                ('set_view', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
