# Generated by Django 2.1.2 on 2019-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kpi', models.IntegerField()),
                ('id_company', models.IntegerField()),
                ('nama_task', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('status', models.IntegerField()),
                ('created_hierarchy', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
