# Generated by Django 2.1.2 on 2019-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='time_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_period', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('stat', models.IntegerField(default=0)),
            ],
        ),
    ]
