# Generated by Django 2.1.2 on 2019-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ssn_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='verfied',
            field=models.IntegerField(default=0),
        ),
    ]
