# Generated by Django 2.1.2 on 2019-01-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='attemp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
