# Generated by Django 2.1.2 on 2019-02-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20190210_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ssn_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='tax_num',
            field=models.CharField(max_length=20),
        ),
    ]
