# Generated by Django 2.1.2 on 2019-01-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_register_attemp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='attemp',
        ),
        migrations.AddField(
            model_name='register',
            name='attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
