# Generated by Django 2.1.2 on 2019-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20190211_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
