# Generated by Django 2.1.2 on 2019-04-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_register_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True)),
                ('status_domoo', models.IntegerField()),
            ],
        ),
    ]
