# Generated by Django 2.1.2 on 2019-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kpi', models.CharField(max_length=255)),
                ('id_goal', models.IntegerField()),
                ('id_company', models.IntegerField()),
                ('standard', models.TextField()),
                ('time_measurement', models.IntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('bobot', models.FloatField()),
                ('create_hierrarchy', models.IntegerField()),
                ('status', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
