# Generated by Django 2.1.2 on 2019-06-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpi',
            old_name='standard',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='kpi',
            old_name='create_hierrarchy',
            new_name='id_kpi_category',
        ),
    ]
