# Generated by Django 2.1.2 on 2019-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hierarchy', models.IntegerField()),
                ('attendance', models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsAdmin'), ('2', 'IsUser')], default='0', max_length=10)),
                ('payroll', models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsAdmin'), ('2', 'IsUser')], default='0', max_length=10)),
                ('status', models.CharField(choices=[('0', 'Unactive'), ('1', 'Active'), ('2', 'Deactive')], default='0', max_length=10)),
                ('expr_date', models.DateField(blank=True, null=True)),
                ('id_comp', models.IntegerField()),
            ],
        ),
    ]
