# Generated by Django 2.1.2 on 2019-04-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensecomp',
            name='id_hierarchy',
            field=models.IntegerField(unique=True),
        ),
    ]
