# Generated by Django 2.1.2 on 2019-04-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_company', '0002_auto_20190402_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecomp',
            name='erp',
            field=models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='licensecomp',
            name='attendance',
            field=models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='licensecomp',
            name='payroll',
            field=models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='0', max_length=10),
        ),
    ]
