# Generated by Django 2.1.2 on 2019-07-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_company', '0003_auto_20190413_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecomp',
            name='billing',
            field=models.IntegerField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='0', max_length=10),
        ),
    ]
