<<<<<<< HEAD
# Generated by Django 2.1.2 on 2019-05-28 05:20
=======
# Generated by Django 2.1.2 on 2019-07-24 06:54
>>>>>>> defacc41181d46d8ea12fa9e6fb832abbd488159

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_company', '0003_auto_20190413_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecomp',
            name='billing',
<<<<<<< HEAD
            field=models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='1', max_length=10),
=======
            field=models.IntegerField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='0', max_length=10),
>>>>>>> defacc41181d46d8ea12fa9e6fb832abbd488159
        ),
    ]
