# Generated by Django 2.1.2 on 2019-07-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_company', '0004_licensecomp_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensecomp',
            name='billing',
            field=models.CharField(choices=[('0', 'IsNothing'), ('1', 'IsUser'), ('2', 'IsAdmin')], default='0', max_length=10),
        ),
    ]
