# Generated by Django 2.1.2 on 2019-08-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license_company', '0005_auto_20190724_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensecomp',
            name='billing',
        ),
    ]
