# Generated by Django 2.1.2 on 2019-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_assign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_assign',
            name='id_kpi',
        ),
        migrations.AddField(
            model_name='kpi_assign',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi_assign',
            name='id_kpi_category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpi_assign',
            name='id_kpi_definition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_assign',
            name='bobot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_assign',
            name='id_company',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_assign',
            name='id_hierarchy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_assign',
            name='id_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpi_assign',
            name='operator',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
