# Generated by Django 2.1.2 on 2019-06-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_goal', models.IntegerField()),
                ('id_company', models.IntegerField()),
                ('id_hierarchy', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('division', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description_key', models.CharField(max_length=255)),
                ('addtional_data', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
